Webmess 725
GenesysCloudBlueprints/messenger-authentication-okta-integration-blueprint pull request #4
Opened 2022-07-18 04:22 UTC by Jayaranjani

2022-07-19 05:02 UTC, ranjithsai requested changes

2022-07-19 05:02 UTC, ranjithsai commented on blueprint/index.md
> +7. For **Grant type**, **Authorization code** is mandatory and check **Refresh token** if required.
@Jayaranjani will we be able to clarify about `Refresh tokens` explicitly explaining how it is optional vs when it will be required?

Also, change text `check` to `select`.

2022-07-19 05:02 UTC, ranjithsai commented on blueprint/index.md
> +	```{"title":"Extracting nonce from session storage","language":"JavaScript"}
Change title to "How to extract nonce from session storage".

2022-07-19 05:02 UTC, ranjithsai commented on blueprint/index.md
> +		let oktaTransactionStorage = window.sessionStorage.getItem("okta-transaction-storage");
please add clear inline comments for each line, explaining what that line of code is doing

2022-07-19 05:02 UTC, ranjithsai commented on blueprint/index.md
> +**Note**: With OKTA SDK approach nonce option is mandatory to resolve [getAuthCode](https://developer.genesys.cloud/api/digital/webmessaging/messengersdk/SDKCommandsEvents#authprovider-plugin "Goes t
Change text `to resolve` to `to resolve in`.

2022-07-19 05:02 UTC, ranjithsai commented on blueprint/index.md
> +	```{"title":"Extracting nonce from session storage","language":"JavaScript"}
There should be a note with in this table saying `nonce ` is mandatory when using OKTA Auth API.

2022-07-20 04:45 UTC, Jayaranjani commented on blueprint/index.md
> +7. For **Grant type**, **Authorization code** is mandatory and check **Refresh token** if required.
@ranjithsai  Corrected it and added NOTE to 'Refresh token'.

2022-07-20 04:45 UTC, Jayaranjani commented on blueprint/index.md
> +	```{"title":"Extracting nonce from session storage","language":"JavaScript"}
@ranjithsai Done

2022-07-20 04:46 UTC, Jayaranjani commented on blueprint/index.md
> +		let oktaTransactionStorage = window.sessionStorage.getItem("okta-transaction-storage");
@ranjithsai Added inline comments.

2022-07-20 04:46 UTC, Jayaranjani commented on blueprint/index.md
> +**Note**: With OKTA SDK approach nonce option is mandatory to resolve [getAuthCode](https://developer.genesys.cloud/api/digital/webmessaging/messengersdk/SDKCommandsEvents#authprovider-plugin "Goes t
@ranjithsai  Done

2022-07-26 04:05 UTC, Jayaranjani commented on blueprint/index.md
> +7. For **Grant type**, **Authorization code** is mandatory and check **Refresh token** if required.
<img width="913" alt="Screenshot 2022-07-26 at 9 32 06 AM" src="https://user-images.githubusercontent.com/100335721/180920585-984dcc3f-bd07-4722-99a0-ec702ac9beef.png">

2022-07-26 04:05 UTC, Jayaranjani commented on blueprint/index.md
> +		let oktaTransactionStorage = window.sessionStorage.getItem("okta-transaction-storage");
<img width="1069" alt="Screenshot 2022-07-26 at 9 35 25 AM" src="https://user-images.githubusercontent.com/100335721/180920640-866339be-1122-4d45-bcc7-ff72ba1ac572.png">

2022-07-26 04:06 UTC, Jayaranjani commented on blueprint/index.md
> +**Note**: With OKTA SDK approach nonce option is mandatory to resolve [getAuthCode](https://developer.genesys.cloud/api/digital/webmessaging/messengersdk/SDKCommandsEvents#authprovider-plugin "Goes t
<img width="1033" alt="Screenshot 2022-07-26 at 9 36 23 AM" src="https://user-images.githubusercontent.com/100335721/180920726-d2382aa8-f804-4243-be53-0c4b3cfe0fa7.png">

2022-08-03 21:16 UTC, ranjithsai approved these changes

2022-08-04 12:24 UTC, RekhaMahalingam approved these changes

2022-08-04 12:25 UTC, merged